### ISSUE TITLE
UE4.26 branch

### ISSUE THREAD

**Issue by Vorlaak** [cgerchenhp/TAPython_DefaultResources#1]
Hi,
Love the work you've been doing as the official PythonAPI documentation on Landscapes isn't clear at all. In the Readme, you say that 'UE4.26, 4.27 branches will coming soon.', is there any news regarding theses branches, especially the 4.26 one ? Thanks

**Comment by cgerchenhp** [comment]
Yes, the documentation does need improvement. For the use of the Landscapes part of the API, you can refer to the _testcase_landscape function in the TestPythonAPIs.py in this repository: https://github.com/cgerchenhp/UE_TAPython_Plugin_TestCases/tree/master

Regarding the 4.26 branch, it is expected to be released within the next two to three days. Thank you for your feedback.

**Comment by Vorlaak** [comment]
Wow, thanks a lot ! Do you know if it is even possible to create a landscape given a heightmap without your plugin and in that case how ?

**Comment by cgerchenhp** [comment]
As far as I know, there is no official API in UE4 for creating landscapes with Python. However, if you can manually create a landscape and then use a Python script to fill in the heightmap, that should be possible. For example, Epic provides the function unreal.LandscapesProxy.landscape_import_heightmap_from_render_target in UE5. （not checked in UE4）

If you can create your own BlueprintLibrary, that would be the most flexible and controllable method. For creating landscapes, you can refer to the code in this repository:https://github.com/sideeffects/HoudiniEngineForUnreal . It includes converting Houdini data to landscapes and filling in heightmaps, etc. It's will be a good reference for you.

**Comment by Vorlaak** [comment]
Thanks a lot again ! What I meant with official API is that when you look at the official python API for the unreal engine, there are classes for landscapes, but when I try to spawn them, it always spawns a LandscapePlaceholder

**Comment by cgerchenhp** [comment]
Yes, but Landscape is a special Actor, we can't create a Landscape directly like we can spawn an Actor.
By the way, the DefaultResources for UE4 branch has been uploaded.

**Comment by Vorlaak** [comment]
Thank you very much !
